"""
AlphaVault Plugin Runner
========================
Loads a third-party bot file, runs it, and generates
trades.csv + zk_input.json ready for on-chain proof submission.

A valid bot file must define:
  BOT_NAME        = "My Bot"          (str)
  INITIAL_CAPITAL = 1000              (float)
  def run() -> list[dict]:            returns list of trade dicts

Each trade dict must have:
  date, asset, action, price, quantity, pnl
"""

import importlib.util
import hashlib
import json
import os
import pandas as pd
from datetime import datetime


REQUIRED_TRADE_FIELDS = {"date", "asset", "action", "price", "quantity", "pnl"}
DAYS = 90


def load_bot(filepath: str):
    """Dynamically load a bot module from a file path."""
    spec = importlib.util.spec_from_file_location("user_bot", filepath)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def validate_bot(module):
    """Check the bot has the required interface."""
    errors = []
    if not hasattr(module, "run"):
        errors.append("Missing run() function")
    if not hasattr(module, "INITIAL_CAPITAL"):
        errors.append("Missing INITIAL_CAPITAL variable")
    if not hasattr(module, "BOT_NAME"):
        errors.append("Missing BOT_NAME variable")
    return errors


def validate_trades(trades: list) -> list:
    """Validate trade records."""
    errors = []
    for i, t in enumerate(trades):
        missing = REQUIRED_TRADE_FIELDS - set(t.keys())
        if missing:
            errors.append(f"Trade #{i+1} missing fields: {missing}")
    return errors


def run_bot_plugin(filepath: str) -> dict:
    """
    Load and run a bot plugin file.
    Returns a result dict with metrics, status, and file paths.
    """
    # Load module
    try:
        module = load_bot(filepath)
    except Exception as e:
        return {"success": False, "error": f"Failed to load bot: {e}"}

    # Validate interface
    errors = validate_bot(module)
    if errors:
        return {"success": False, "error": "; ".join(errors)}

    bot_name = module.BOT_NAME
    initial_capital = float(module.INITIAL_CAPITAL)

    # Run the bot
    try:
        trades = module.run()
    except Exception as e:
        return {"success": False, "error": f"Bot run() raised an error: {e}"}

    if not isinstance(trades, list) or len(trades) == 0:
        return {"success": False, "error": "run() must return a non-empty list of trades"}

    # Validate trade records
    trade_errors = validate_trades(trades)
    if trade_errors:
        return {"success": False, "error": "; ".join(trade_errors)}

    # Build dataframe
    df = pd.DataFrame(trades)
    df["pnl"] = pd.to_numeric(df["pnl"], errors="coerce").fillna(0)

    # Compute metrics
    total_profit = round(df["pnl"].sum(), 4)
    final_value  = round(initial_capital + total_profit, 2)
    total_trades = len(df)
    wins         = df[df["pnl"] > 0]
    win_rate     = round(len(wins) / total_trades * 100, 1) if total_trades else 0

    net_pnl_fp   = int(total_profit * 1000)
    capital_fp   = int(initial_capital * 1000)

    # Compute APY bps to match the ZK circuit exactly:
    # circuit checks: |netPnl * 365 * 10000 - newApy * capital * period| <= capital * period
    # So newApy must be the rounded result of (netPnl * 365 * 10000) / (capital * period)
    if capital_fp > 0:
        numerator   = net_pnl_fp * 365 * 10000
        denominator = capital_fp * DAYS
        # Use round() not floor to stay within ±1 denominator tolerance
        apy_bps = round(numerator / denominator)
    else:
        apy_bps = 0

    # For the contract (Uint<32>), clamp negative to 0
    # but keep the real value for display
    apy_bps_display = apy_bps
    apy_bps_onchain = max(0, apy_bps)

    # SHA-256 of trades CSV — this is the tradeDataCommitment
    csv_bytes   = df.to_csv(index=False).encode("utf-8")
    trade_hash  = hashlib.sha256(csv_bytes).hexdigest()

    # Save files
    os.makedirs("data", exist_ok=True)
    df.to_csv("data/trades.csv", index=False)

    metrics = {
        "strategy":             bot_name,
        "initial_capital":      initial_capital,
        "final_value":          final_value,
        "total_profit":         total_profit,
        "apy_percent":          round(apy_bps_display / 100, 2),
        "max_drawdown_percent": 0,
        "win_rate_percent":     win_rate,
        "sharpe_ratio":         0,
        "total_trades":         total_trades,
    }
    with open("data/metrics.json", "w") as f:
        json.dump(metrics, f, indent=2)

    zk_input = {
        "privateNetPnl":      abs(net_pnl_fp),   # Uint<64> — always positive
        "privateCapital":     capital_fp,
        "privateTradePeriod": DAYS,
        "privateTradeCount":  total_trades,
        "submittedApyBps":    apy_bps_onchain,    # Uint<32> — clamped to 0 if negative
        "tradeDataHash":      trade_hash,
        "description":        f"Generated by {bot_name} at {datetime.now().isoformat()}",
    }
    with open("data/zk_input.json", "w") as f:
        json.dump(zk_input, f, indent=2)

    # Build equity curve for dashboard
    equity = [initial_capital]
    running = initial_capital
    daily = {}
    for _, row in df.iterrows():
        running += row["pnl"]
        daily[str(row["date"])] = round(running, 2)
        equity.append(round(running, 2))

    with open("data/equity_curve.json", "w") as f:
        json.dump(equity, f)
    with open("data/daily_equity.json", "w") as f:
        json.dump(daily, f)

    return {
        "success":       True,
        "botName":       bot_name,
        "totalTrades":   total_trades,
        "totalProfit":   total_profit,
        "finalValue":    final_value,
        "apyPercent":    round(apy_bps_display / 100, 2),
        "winRate":       win_rate,
        "tradeDataHash": trade_hash,
        "apyBps":        apy_bps_onchain,
    }
